//! Vendor-quirk tolerance — whole-line `;` and `#` comments in
//! ASCII STL files.
//!
//! Some hand-edited STL files and a handful of vintage CAD
//! exporters insert annotation comments between facets or at the
//! top of the file. The 1989 spec defines no comment syntax, but the
//! dominant real-world tolerance is to skip whole-line comments
//! starting with `;` (sometimes `#`). The parser (and the
//! ASCII-vs-binary sniffer) treats both as line-comment introducers
//! at token boundaries.

use oxideav_mesh3d::Mesh3DDecoder;
use oxideav_stl::StlDecoder;

#[test]
fn semicolon_comment_at_top_of_file_is_accepted() {
    let s = "; generated by hand 2026-05-11\n\
             ; second comment line\n\
             solid t\n\
             facet normal 0 0 1\n\
             outer loop\n\
             vertex 0 0 0\n\
             vertex 1 0 0\n\
             vertex 0 1 0\n\
             endloop\n\
             endfacet\n\
             endsolid t\n";
    let scene = StlDecoder::new().decode(s.as_bytes()).unwrap();
    assert_eq!(scene.meshes.len(), 1);
    let p = &scene.meshes[0].primitives[0];
    assert_eq!(p.positions.len(), 3);
}

#[test]
fn hash_comment_at_top_of_file_is_accepted() {
    let s = "# generated by some hand-rolled tool\n\
             solid t\n\
             facet normal 0 0 1\n\
             outer loop\n\
             vertex 0 0 0\n\
             vertex 1 0 0\n\
             vertex 0 1 0\n\
             endloop\n\
             endfacet\n\
             endsolid t\n";
    let scene = StlDecoder::new().decode(s.as_bytes()).unwrap();
    assert_eq!(scene.meshes.len(), 1);
}

#[test]
fn comment_between_facets_is_skipped() {
    let s = "solid t\n\
             facet normal 0 0 1\n\
             outer loop\n\
             vertex 0 0 0\n\
             vertex 1 0 0\n\
             vertex 0 1 0\n\
             endloop\n\
             endfacet\n\
             ; this is the second triangle\n\
             facet normal 0 0 1\n\
             outer loop\n\
             vertex 1 0 0\n\
             vertex 1 1 0\n\
             vertex 0 1 0\n\
             endloop\n\
             endfacet\n\
             endsolid t\n";
    let scene = StlDecoder::new().decode(s.as_bytes()).unwrap();
    let p = &scene.meshes[0].primitives[0];
    assert_eq!(p.positions.len(), 6);
}

#[test]
fn multi_comment_blocks_are_all_skipped() {
    // Multiple introducer characters back-to-back stress the
    // skip-ws loop's whitespace + comment-line alternation.
    let s = ";; first\n\
             ## second\n\
             ; third\n\
             solid t\n\
             facet normal 0 0 1\n\
             outer loop\n\
             vertex 0 0 0\n\
             vertex 1 0 0\n\
             vertex 0 1 0\n\
             endloop\n\
             endfacet\n\
             endsolid t\n";
    let scene = StlDecoder::new().decode(s.as_bytes()).unwrap();
    assert_eq!(scene.meshes.len(), 1);
}

#[test]
fn comment_starting_with_bom_and_whitespace_is_accepted() {
    // UTF-8 BOM + leading newlines + comments + leading whitespace
    // — the prefix sniff and parser both have to tolerate this
    // combination.
    let mut buf: Vec<u8> = Vec::new();
    buf.extend_from_slice(&[0xEF, 0xBB, 0xBF]);
    buf.extend_from_slice(b"\n  ; comment\n");
    buf.extend_from_slice(
        b"solid t\n\
          facet normal 0 0 1\n\
          outer loop\n\
          vertex 0 0 0\n\
          vertex 1 0 0\n\
          vertex 0 1 0\n\
          endloop\n\
          endfacet\n\
          endsolid t\n",
    );
    let scene = StlDecoder::new().decode(&buf).unwrap();
    assert_eq!(scene.meshes.len(), 1);
}
